wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717699840
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.10
      5: 0.17.0
      8:
      - 5
      13: darwin-x86_64
